// Mocks generated by Mockito 5.4.4 from annotations
// in ene_test/test/mock_workspace_repo.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ene_test/features/workspace/domain/entities/workspace.dart'
    as _i4;
import 'package:ene_test/features/workspace/domain/repos/workspace_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkspaceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceRepo extends _i1.Mock implements _i2.WorkspaceRepo {
  MockWorkspaceRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Workspace>> getWorkspaces() => (super.noSuchMethod(
        Invocation.method(
          #getWorkspaces,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Workspace>>.value(<_i4.Workspace>[]),
      ) as _i3.Future<List<_i4.Workspace>>);

  @override
  _i3.Future<void> addWorkspace(_i4.Workspace? workspace) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWorkspace,
          [workspace],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeWorkspace(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeWorkspace,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Workspace>> searchWorkspaces(String? searchText) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchWorkspaces,
          [searchText],
        ),
        returnValue: _i3.Future<List<_i4.Workspace>>.value(<_i4.Workspace>[]),
      ) as _i3.Future<List<_i4.Workspace>>);
}
